config/routes.rb
Socalbouldering::Application.routes.draw do

  resources :forums do
    resources :topics do
      resources :posts
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  root :to => 'forums#index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :topics, :dependent => :destroy

  validates_presence_of :name
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  respond_to :html, :json
  load_and_authorize_resource except: [:index, :show]

  def index
    @forums = Forum.order(:name).includes(:topics)
    respond_with @forums
  end

  def show
    @forum = Forum.find(params[:id])
    @topics = @forum.topics.order("created_at DESC").paginate(page: params[:page])
    respond_with @forum
  end

  def new
    @forum = Forum.new
  end

  def edit
  end

  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render json: @forum, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private

    def forum_params
      params.require(:forum).permit(:name, :description)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.haml
= simple_form_for(@forum) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/forums/edit.html.haml
%h1 Editing forum

= render 'form'

.pull-right
  = link_to "Delete Forum", forum_path(@forum), method: :delete, confirm: "Are you sure?"
= link_to 'Back', forums_path

app/views/forums/index.html.haml
%h1 Say it!

%table.table.table-striped.table-bordered
  %tr
    %th Forum
    %th Topics
    %th Posts
    %th Last Post

  - @forums.each do |forum|
    %tr
      %td
        = link_to forum.name, forum
        %br
        = forum.description
      %td= forum.topics.count
      %td= forum.topics.sum(:posts_count)
      %td= l(forum.topics.order("updated_at DESC").first.updated_at, format: :medium ) rescue "---"

%br
- if can? :create, Forum
  = link_to "New forum", new_forum_path

app/views/forums/new.html.haml
%h1 New forum

= render 'form'

= link_to 'Back', forums_path

app/views/forums/show.html.haml
%h1= @forum.name

- if can? :create, Topic
  .pull-right
    = link_to 'New Topic', new_forum_topic_path(@forum)
    - if can? :manage, Forum
      \|
      = link_to 'Edit Forum', edit_forum_path(@forum)

%table.table.table-striped.table-bordered
  %tr
    %th Topics
    %th Author
    %th Replies
    %th Views
    %th Last Post
  - @topics.each do |topic|
    %tr
      %td= link_to topic.title, [@forum, topic]
      %td= topic.user.username
      %td= topic.posts.count
      %td= topic.views
      %td= l(topic.last_post.created_at, format: :medium) rescue "---"

= will_paginate @topics