config/routes.rb
Socalbouldering::Application.routes.draw do

  resources :forums do
    resources :topics do
      resources :posts
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  root :to => 'forums#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :forum
  belongs_to :user
  has_many :posts, :inverse_of => :topic, :dependent => :destroy

  validates_numericality_of :forum_id, :user_id, :posts_count
  validates_presence_of :title

  accepts_nested_attributes_for :posts

  def last_post
    self.posts.order("created_at DESC").first
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  respond_to :html, :json
  before_filter :load_data
  load_and_authorize_resource except: [:index, :show]

  def index
    @topics = @forum.topics
    respond_with @topics
  end

  def show
    @posts = @topic.posts.order(:created_at).includes(:user).paginate(page: params[:page])
    @topic.increment!(:views)
    respond_with @topic
  end

  def new
    @topic = Topic.new
    @post = @topic.posts.new
  end

  def edit
  end

  def create
    params[:topic][:posts_attributes].each do |k, v|
      params[:topic][:posts_attributes][k]["user_id"] = current_user.id
    end

    @topic = @forum.topics.new(topic_params)
    @topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        format.html { redirect_to [@forum, @topic], notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(topic_params)
        format.html { redirect_to [@forum, @topic], notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to forum_url(@topic.forum) }
      format.json { head :no_content }
    end
  end

  private
    def load_data
      @forum = Forum.find(params[:forum_id])
      @topic = @forum.topics.find(params[:id]) if params[:id]
    end

    def topic_params
      params.require(:topic).permit(:title, posts: [:content])
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
= form_for([@forum, @topic]) do |f|
  - if @topic.errors.any?
    #errorExplanation.errorExplanation
      - @topic.errors.full_messages.each do |msg|
        %p.text-error= msg

  .form-inputs
    = f.label :title
    = f.text_field :title

  - if @topic.new_record?
    .form-inputs{style: "margin-top: 20px"}
      = f.fields_for :posts, @post do |posts_form|
        = render "application/wysihtml"
        = posts_form.text_area :content, id: "wysihtml5-textarea"

  .form-actions
    %button.btn Create Topic

app/views/topics/edit.html.haml
%h1 Editing topic

= render 'form'

.pull-right
  = link_to "Delete topic", forum_topic_path(@forum, @topic), method: :delete, confirm: "Are you sure?"
= link_to 'Back', :back

app/views/topics/index.html.haml
%h1 Listing topics

%table.table.table-striped.table-bordered
  %tr
    %th Forum
    %th Title
    %th User
    %th Views
    %th
    %th
    %th

  - @topics.each do |topic|
    %tr
      %td= topic.forum_id
      %td= topic.title
      %td= topic.user_id
      %td= topic.views
      %td= link_to 'Show', topic
      %td= link_to 'Edit', edit_topic_path(topic)
      %td= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
%h1 New topic

= render 'form'

= link_to 'Back', forum_path(@forum)

app/views/topics/show.html.haml
%h2= @topic.title

%ul.breadcrumb
  %li
    = link_to "Home", root_path
    %span.divider /
  %li
    = link_to @topic.forum.name, @forum

- if can? :create, Post
  .pull-right
    = link_to "Post Reply", new_forum_topic_post_path(@forum, @topic)
    - if can? :manage, @topic
      \|
      = link_to "Edit Topic", edit_forum_topic_path(@forum, @topic)


%table#posts.table.table-striped.table-bordered
  %tr
    %th Author
    %th Message
  - @posts.each do |post|
    %tr
      %td
        = gravatar_for(post.user, 100)
        %br
        = post.user
      %td
        - markdown = Redcarpet::Markdown.new(MdEmoji::Render, :no_intra_emphasis => true)
        != markdown.render(post.content)
        .pull-left.post-details
          - if can? :manage, post
            = link_to "Edit post", edit_forum_topic_post_path(@forum, @topic, post)
        .pull-right.post-details
          %span.label
            - if post.created_at <= 3.days.ago
              = l(post.created_at, format: :medium)
            - else
              #{time_ago_in_words(post.created_at)} ago


- if can? :create, Post
  .pull-right= link_to "Post Reply", new_forum_topic_post_path(@forum, @topic)

= will_paginate @posts