config/routes.rb
Socalbouldering::Application.routes.draw do

  resources :forums do
    resources :topics do
      resources :posts
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  root :to => 'forums#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic, :inverse_of => :posts
  belongs_to :user, :inverse_of => :posts

  validates_presence_of :user_id, :topic_id, :content

  after_save :update_topic_posts_count

  private
    def update_topic_posts_count
      self.topic.increment(:posts_count)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json
  before_filter :load_data
  load_and_authorize_resource except: [:index, :show]

  def index
    @posts = @topic.posts
    respond_with @posts
  end

  def show
    respond_with @post
  end

  def new
    @post = @topic.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
  end

  def create
    @post = @topic.posts.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@forum, @topic], notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to [@forum, @topic], notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to [@forum, @topic], notice: "Post deleted." }
      format.json { head :no_content }
    end
  end

  private
    def load_data
      @forum = Forum.find(params[:forum_id])
      @topic = @forum.topics.find(params[:topic_id]) if params[:topic_id]
      @post = @topic.posts.find(params[:id]) if params[:id]
    end

    def post_params
      params.require(:post).permit(:content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for([@forum, @topic, @post]) do |f|
  - if @post.errors.any?
    #errorExplanation.errorExplanation
      - @post.errors.full_messages.each do |msg|
        %p.text-error= msg

  .form-inputs
    = render "application/wysihtml"
    = f.text_area :content, id: "wysihtml5-textarea"
    -#= f.input :content, :label => nil, :required => false, :input_html => {id: "wysihtml5-textarea", autofocus: true}

  .form-actions
    %button.btn Create Post

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

.pull-right
  = link_to "Delete Post", forum_topic_post_path(@forum, @topic, @post), method: :delete, confirm: "Are you sure?"
= link_to 'Back', :back

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Topic
    %th User
    %th Content
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.topic_id
      %td= post.user_id
      %td= post.content
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', :back