config/routes.rb
Socalbouldering::Application.routes.draw do

  resources :forums do
    resources :topics do
      resources :posts
    end
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  root :to => 'forums#index'

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title Socal Bouldering
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    / Le styles
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = render "application/google_analytics"

  %body.container-fluid
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to Settings.site_title, root_path, class: "brand"
          .nav-collapse.collapse
            / %ul.nav
            /   %li.active
            /     %a{:href => "#about"} About
            /   %li
            /     %a{:href => "#contact"} Contact
            %ul.nav.pull-right
              - if user_signed_in?
                %li= link_to "Welcome, #{current_user.username}", edit_registration_path(current_user)
                %li= link_to "Sign out", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Sign up", new_user_registration_path
                %li= link_to "Sign in", new_user_session_path
          / /.nav-collapse
    .container
      .row
        - if notice
          .alert.alert-success
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = notice
        - if alert
          .alert.alert-error
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = alert
      .row=yield
      %hr
      %footer
        Copyright &copy; #{Time.now.year} - #{Settings.owner_name}


  = javascript_include_tag "application"